# Site settings
title: UC Davis iGem Wiki
email: ucdigem@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/UCDiGEM2016.io/" # the subpath of your site, e.g. /blog/
url: "https://ucdigem2016.github.io/UCDiGEM2016.io" # the base hostname & protocol for your site
twitter_username: UC_Davis_iGem
github_username:  akre96

# Build settings
markdown: kramdown
